lang: en
execute:
  freeze: auto

project:
  type: website
  resources: 
    - images/
  preview: 
      port: 3333

website:
  title: ""
  image: "images/gitbook.svg"
  favicon: "images/favicon.png"
  site-url: "https://github.com/"
  description: "my personal web page build with quarto"
  open-graph: true
  twitter-card: true
  reader-mode: true
  page-navigation: true
  search: true
  navbar:
    pinned: true
    logo: "images/gitbook.svg"
    right:
      - text: "Blog"
        file: blog.qmd
      - text: "Docs"
        file: docs.qmd
      - text: "About"
        file: index.qmd
      - icon: github
        href: https://github.com
      
  
  sidebar:
    - title: "Blog"
      style: docked
      contents: 
        - auto: posts/

  page-footer: 
    left: "Made with ❤️ by [ivansaul](https://github.com/ivansaul)"  
    center:
      - text: "Blog"
        file: blog.qmd
      - text: "Docs"
        file: docs.qmd
      - text: "About"
        file: index.qmd
    right: 
      - icon: github
        href: https://github.com/
      - icon: twitter 
        href: https://twitter.com/ 

format:
  html:
    theme: 
      dark: solar
      light: litera
    css: styles.css
    toc: true
    highlight-style: monokai
    code-copy: true
    code-overflow: wrap